name: 'Set up compiler'
description: 'Setup compiler.'

inputs:
  cache-suffix:
    description: 'Cannot have a common cache within one workflow'
    required: true
  target:
    description: 'Target'
    default: x86_64
    required: false

runs:
  using: "composite"
  steps:
      - name: Cache build dir
        uses: actions/cache@v4.2.0
        id: compiler-cache
        with:
          key: setup-compiler-v3-${{inputs.cache-suffix}}
          path: |
            /usr/local/miniconda/envs
      - uses: conda-incubator/setup-miniconda@v3.0.4
        with:
          auto-update-conda: true
          python-version: 3.8
          channels: anaconda, conda-forge
          activate-environment: compiler
          conda-solver: libmamba
        env:
          CONDA_SUBDIR: ${{ inputs.target == 'x86_64' && 'osx-64' || 'osx-arm64'  }}
      - run: |
             wget https://github.com/phracker/MacOSX-SDKs/releases/download/11.0-11.1/MacOSX11.1.sdk.tar.xz
             sudo tar xf MacOSX11.1.sdk.tar.xz -C /opt
             conda config --env --set subdir ${{ inputs.target == 'x86_64' && 'osx-64' || 'osx-arm64'  }} osx-arm64
             conda install -y -c conda-forge libcxx==16.0.6 libgfortran\<13 libgfortran5\<13 c-compiler==1.6.0 cxx-compiler==1.6.0 fortran-compiler==1.6.0 bzip2==1.0.8 # was 1.5.2
             
             echo "SDKROOT=/opt/MacOSX11.1.sdk" >> $GITHUB_ENV
             echo "CONDA_BUILD_SYSROOT=/opt/MacOSX11.1.sdk" >> $GITHUB_ENV
             echo "MACOSX_DEPLOYMENT_TARGET=11.0" >> $GITHUB_ENV
             echo "CONDA_SUBDIR=${{ inputs.target == 'x86_64' && 'osx-64' || 'osx-arm64'  }}" >> $GITHUB_ENV
        if: steps.compiler-cache.outputs.cache-hit != 'true'
        shell: bash -el {0}
      - run: |
             echo "CC=$CONDA_PREFIX/bin/clang" >> $GITHUB_ENV
             echo "CXX=$CONDA_PREFIX/bin/clang++" >> $GITHUB_ENV
             echo "FC=$CONDA_PREFIX/bin/gfortran" >> $GITHUB_ENV
             echo "COMPILER_LIB_SEARCH_PATH=$CONDA_PREFIX/lib" >> $GITHUB_ENV
        shell: bash -el {0}
