name: 'Set up compiler'
description: 'Setup compiler.'

inputs:
  cache-suffix:
    description: 'Cannot have a common cache within one workflow'
    required: true
  target:
    description: 'Target'
    default: x86_64
    required: false

env:
  CONDA_DEFAULT_ENV: __setup_conda

runs:
  using: "composite"
  steps:
      - name: Cache build dir
        uses: actions/cache@v2
        id: compiler-cache
        with:
          key: setup-compiler-v2-${{inputs.cache-suffix}}
          path: /usr/local/miniconda/envs/${{env.CONDA_DEFAULT_ENV}}
      - name: Setup conda
        if: steps.compiler-cache.outputs.cache-hit != 'true'
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.8
          conda-channels: anaconda, conda-forge
      - run: |
             # https://stackoverflow.com/questions/69236331/conda-macos-big-sur-ld-unsupported-tapi-file-type-tapi-tbd-in-yaml-file
             wget https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.9.sdk.tar.xz
             sudo tar xf MacOSX10.9.sdk.tar.xz -C /opt
             
             conda install -y -c conda-forge c-compiler==1.1.1 cxx-compiler==1.1.1 fortran-compiler==1.1.1
             
        if: steps.compiler-cache.outputs.cache-hit != 'true'
        if: target == 'x86_64'
        shell: bash
      - run: |
             
             conda install -y -c conda-forge gfortran_osx-arm64==11.3.0 clangxx_osx-arm64==11.1.0 clang_osx-arm64==11.1.0
             
        if: steps.compiler-cache.outputs.cache-hit != 'true'
        if: target == 'arm64'
        shell: bash
      - run: |
             echo "CC=/usr/local/miniconda/envs/${{env.CONDA_DEFAULT_ENV}}/bin/clang" >> $GITHUB_ENV
             echo "CXX=/usr/local/miniconda/envs/${{env.CONDA_DEFAULT_ENV}}/bin/clang++" >> $GITHUB_ENV
             echo "FC=/usr/local/miniconda/envs/${{env.CONDA_DEFAULT_ENV}}/bin/gfortran" >> $GITHUB_ENV
        if: target == 'x86_64'
        shell: bash
      - run: |
             echo "CC=/usr/local/miniconda/envs/${{env.CONDA_DEFAULT_ENV}}/bin/arm64-appple-darwin20.0.0-clang" >> $GITHUB_ENV
             echo "CXX=/usr/local/miniconda/envs/${{env.CONDA_DEFAULT_ENV}}/bin/arm64-appple-darwin20.0.0-clang++" >> $GITHUB_ENV
             echo "FC=/usr/local/miniconda/envs/${{env.CONDA_DEFAULT_ENV}}/bin/arm64-appple-darwin20.0.0-gfortran" >> $GITHUB_ENV
        if: target == 'arm64'
        shell: bash
