name: 'Set up compiler'
description: 'Setup compiler.'

inputs:
  cache-suffix:
    description: 'Cannot have a common cache within one workflow'
    required: true
  target:
    description: 'Target'
    default: x86_64
    required: false

runs:
  using: "composite"
  steps:
      - name: Cache build dir
        uses: actions/cache@v3.2.3
        id: compiler-cache
        with:
          key: setup-compiler-v3-${{inputs.cache-suffix}}
          path: |
            /usr/local/miniconda/envs
      - uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          auto-update-conda: true
          python-version: 3.8
          channels: anaconda, conda-forge
          activate-environment: compiler
      - run: |
             # https://stackoverflow.com/questions/69236331/conda-macos-big-sur-ld-unsupported-tapi-file-type-tapi-tbd-in-yaml-file
             wget https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.9.sdk.tar.xz
             sudo tar xf MacOSX10.9.sdk.tar.xz -C /opt
             
             conda install -y -c conda-forge c-compiler==1.1.1 cxx-compiler==1.1.1 fortran-compiler==1.1.1
             
             echo "SDKROOT=/opt/MacOSX10.9.sdk" >> $GITHUB_ENV
        if: steps.compiler-cache.outputs.cache-hit != 'true' && inputs.target == 'x86_64'
        shell: bash -el {0}
      - run: |
             wget https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.9.sdk.tar.xz
             sudo tar xf MacOSX10.9.sdk.tar.xz -C /opt
             
             conda install -y -c conda-forge gfortran_osx-arm64==11.3.0 clangxx_osx-arm64==11.1.0 clang_osx-arm64==11.1.0
             
             echo "SDKROOT=/opt/MacOSX10.9.sdk" >> $GITHUB_ENV
             echo "CONDA_BUILD_SYSROOT=/opt/MacOSX10.9.sdk" >> $GITHUB_ENV
        if: false && steps.compiler-cache.outputs.cache-hit != 'true' && inputs.target == 'arm64'
        shell: bash -el {0}
      - run: |
             wget https://github.com/phracker/MacOSX-SDKs/releases/download/11.0-11.1/MacOSX11.1.sdk.tar.xz
             sudo tar xf MacOSX11.1.sdk.tar.xz -C /opt
             
             conda install -y -c conda-forge c-compiler==1.5.2 cxx-compiler==1.5.2 fortran-compiler==1.5.2
             
             echo "SDKROOT=/opt/MacOSX11.1.sdk" >> $GITHUB_ENV
             echo "CONDA_BUILD_SYSROOT=/opt/MacOSX11.1.sdk" >> $GITHUB_ENV
        if: steps.compiler-cache.outputs.cache-hit != 'true' && inputs.target == 'arm64'
        shell: bash -el {0}
      - run: |
             echo "CC=$CONDA_PREFIX/bin/clang" >> $GITHUB_ENV
             echo "CXX=$CONDA_PREFIX/bin/clang++" >> $GITHUB_ENV
             echo "FC=$CONDA_PREFIX/bin/gfortran" >> $GITHUB_ENV
             echo "COMPILER_LIB_SEARCH_PATH=$CONDA_PREFIX/lib" >> $GITHUB_ENV
        shell: bash -el {0}
      - run: |
             echo "CC=${{env.CONDA_PREFIX}}/bin/arm64-appple-darwin20.0.0-clang" >> $GITHUB_ENV
             echo "CXX=${{env.CONDA_PREFIX}}/bin/arm64-appple-darwin20.0.0-clang++" >> $GITHUB_ENV
             echo "FC=${{env.CONDA_PREFIX}}/bin/arm64-appple-darwin20.0.0-gfortran" >> $GITHUB_ENV
        if: false && inputs.target == 'arm64'
        shell: bash -el {0}
